build-job:
  stage: build
  script: 
    - echo "hello , $GITLAB_USER_LOGIN!"


test-job1:
  stage: test
  script: 
    - echo "this job tests somthing"

test-job1:
  stage: test
  script: 
    - echo "this job tests somthing, but takes more time than test job1"
    - echo "this job tests somthing, but takes more time than test job1"
    - echo "this job tests somthing, but takes more time than test job1"
    - spleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "this job tests somthing, but takes more time than test job1"
  environment: production